### ISSUE TITLE
Relational Model

### ISSUE THREAD

**Issue by OwenHernandez** [Angel-L-G/Brawle#1]
Make the relational model of the ddbb

**Comment by Joelyx** [comment]
@Angel-L-G The foreing keys shoudn't be shown in races, gender and year
![Captura de pantalla 2023-06-21 173541](https://github.com/Angel-L-G/Brawle/assets/100943508/c72ea853-411d-4622-a01d-6ff98d166f2c)

**Comment by Joelyx** [comment]
The same can be said for weapons and games
![Captura de pantalla 2023-06-21 173908](https://github.com/Angel-L-G/Brawle/assets/100943508/6e57f516-478c-4e79-86ff-f87d9911f0be)
![Captura de pantalla 2023-06-21 173933](https://github.com/Angel-L-G/Brawle/assets/100943508/b5e6a25c-223f-4e26-b3e9-0b2f190f1cfa)

**Comment by Joelyx** [comment]
#13 Possible solution

**Comment by OwenHernandez** [comment]
some other issues in the entity-relationship and relational model #14

**Comment by Joelyx** [comment]
Database structure defined

**Comment by OwenHernandez** [comment]
some other more issues found on the MR model

**Comment by OwenHernandez** [comment]
fix: they are fixed now #1
